rm Action_and_Adventure.txt
rm Anime_and_Animation.txt
rm Blu-ray.txt
rm Children_and_Family.txt
rm Classics.txt
rm Comity.txt
rm Documentary.txt
rm Drama.txt
rm Faith_and_spirituality.txt
rm Foreign.txt
rm Gay_and_lesbian.txt
rm Horror.txt
rm Independent.txt
rm Music_and_Musicals.txt
rm Romance.txt
rm Sci-Fi_and_fantasy.txt
rm Special_Interests.txt
rm Sports_and_Fitness.txt
rm Television.txt
rm Thrillers.txt
